import 'dart:math';

/// Standard Diceware word list subset for generating short, readable, random filenames.
const List<String> dicewareWords = [
  'ancla',
  'manzana',
  'flecha',
  'insignia',
  'estandarte',
  'tocino',
  'brisa',
  'puente',
  'bronce',
  'cañón',
  'castillo',
  'cedro',
  'centro',
  'encanto',
  'trébol',
  'cobalto',
  'cometa',
  'cobre',
  'coral',
  'cosmos',
  'cráter',
  'cristal',
  'ciprés',
  'delta',
  'desierto',
  'diamante',
  'dominio',
  'dragón',
  'águila',
  'eco',
  'ascua',
  'esmeralda',
  'halcón',
  'pluma',
  'bosque',
  'fuente',
  'galaxia',
  'jardín',
  'granate',
  'glaciar',
  'puerto',
  'refugio',
  'gavilán',
  'avellana',
  'brezo',
  'horizonte',
  'isla',
  'marfil',
  'jade',
  'jaspe',
  'jungla',
  'laguna',
  'farol',
  'laurel',
  'leyenda',
  'loto',
  'pradera',
  'meteoro',
  'espejismo',
  'monarca',
  'montaña',
  'nebulosa',
  'oasis',
  'océano',
  'oliva',
  'ópalo',
  'orquídea',
  'órbita',
  'nutria',
  'palacio',
  'pantera',
  'guijarro',
  'fénix',
  'planeta',
  'prisma',
  'cuarzo',
  'cuervo',
  'cresta',
  'río',
  'rubí',
  'silla',
  'safari',
  'sáhara',
  'salmón',
  'zafiro',
  'sombra',
  'escudo',
  'sierra',
  'plata',
  'horizonte',
  'solsticio',
  'chispa',
  'pícea',
  'estrella',
  'piedra',
  'cumbre',
  'atardecer',
  'trueno',
  'madera',
  'topacio',
  'faro',
  'valle',
  'terciopelo',
  'navío',
  'violeta',
  'volcán',
  'viaje',
  'nogal',
  'sauce',
  'viento',
  'sabiduría',
  'cenit',
];

/// Generates a random 3-word slug joined by hyphen using Random.secure().
/// Example output: `velvet-orchid-harbor`
String generateDicewareName() {
  final rng = Random.secure();
  final word1 = dicewareWords[rng.nextInt(dicewareWords.length)];
  final word2 = dicewareWords[rng.nextInt(dicewareWords.length)];
  final word3 = dicewareWords[rng.nextInt(dicewareWords.length)];
  return '$word1-$word2-$word3';
}

/// Generates a single capitalized random Diceware word.
/// Example output: `Esmeralda`
String generateRandomSingleWord() {
  final rng = Random.secure();
  final word = dicewareWords[rng.nextInt(dicewareWords.length)];
  if (word.isEmpty) return 'Nodo';
  return word[0].toUpperCase() + word.substring(1);
}
